# Practical_6: Numpy

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
import numpy as np 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [2]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [3]:
np.linspace(0,5 , 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [5]:
np.random.random((4,4))

array([[0.76203122, 0.67836873, 0.10308474, 0.39504671],
       [0.80244471, 0.60211534, 0.65595132, 0.84906965],
       [0.92408312, 0.35816248, 0.35159156, 0.81063232],
       [0.29396976, 0.84339413, 0.09621087, 0.66432643]])

### Exercise 6:
Find the shape of a NumPy array.

In [6]:
a  = np.array([1,23,4])
np.shape(a)

(3,)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [7]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

In [8]:
n = np.arange(1,12)
n.dtype

dtype('int64')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [9]:
np.arange(1,101)[1::2]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [10]:
np.random.randint(10,51, size = (6,6))

array([[12, 15, 25, 49, 47, 12],
       [29, 48, 50, 31, 21, 17],
       [44, 11, 24, 23, 44, 27],
       [46, 21, 29, 22, 26, 15],
       [47, 21, 45, 44, 49, 42],
       [16, 22, 21, 34, 25, 11]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [11]:
np.array([1,2,3,4,5]).sum()

15

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [12]:
a = np.random.randint(1,100 , size=(1,14))
a

array([[ 8, 23, 79, 70, 58, 36, 89, 19, 85, 29, 17, 22, 77, 75]])

In [13]:
np.mean(a)   # compute the mean of a 

49.07142857142857

In [14]:
np.median(a)  # compute the median of a 

47.0

In [15]:
np.sqrt(np.var(a))  #compute the standart diviation of a by using the square root of a 

28.481734211130288

In [16]:
np.std(a)     #compute the standart diaviation of a by using std() method in numpy 

28.481734211130288

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [17]:
a = np.random.randint(20,41, size = (1,5))
a

array([[29, 34, 20, 21, 39]])

In [18]:
a1 = np.random.randint(20,41, size = (4,5))

In [19]:
a1

array([[37, 37, 40, 20, 36],
       [30, 25, 36, 29, 28],
       [34, 21, 22, 25, 23],
       [33, 29, 32, 27, 24]])

In [20]:
np.max(a1 , axis = 0)     # max for each rows

array([37, 37, 40, 29, 36])

In [21]:
np.min(a1, axis = 1)      # min for each coloumns

array([20, 25, 21, 24])

In [22]:
np.min(a)

20

In [23]:
np.max(a)

39

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [24]:
b = np.random.randint(0,21 , size = (3,4))

In [25]:
b

array([[ 8, 18, 18, 11],
       [11, 10, 15, 15],
       [14, 10,  8,  3]])

In [26]:
np.argmax(b)     # use argmin for finding th index of minumum value in b

1

### Exercise 16:
Create a NumPy array and reverse its elements.

In [27]:
s = np.array([2,3,4,5])
s[::-1]      #reverse the array s 

array([5, 4, 3, 2])

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [28]:
m1 = np.random.randint(4,9, size = (3,3))
m2 = np.random.randint(11,21, size = (3,3))

In [29]:
m1

array([[7, 8, 8],
       [7, 5, 6],
       [6, 5, 5]])

In [30]:
m2

array([[18, 17, 20],
       [17, 17, 14],
       [12, 11, 17]])

In [31]:
m1*m2  #sum element by element of array m1 amd array m2

array([[126, 136, 160],
       [119,  85,  84],
       [ 72,  55,  85]])

### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [32]:
m =np.random.randint(1,6 , size = (1,4))[0]

In [33]:
m

array([2, 3, 5, 2])

In [34]:
np.diag(m)    # create the diagonal matrix from the 1D array m 

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 2]])

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [35]:
matrice1 = np.random.randint(2,4 ,size = (3,5))
matrice2 = np.random.randint(6,8 , size = (5,3))

In [36]:
matrice1.dot(matrice2)

array([[83, 80, 89],
       [90, 86, 95],
       [77, 74, 82]])

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [37]:
oneDa = np.random.random((3,5))

In [38]:
oneDa

array([[0.59623166, 0.92751023, 0.78838537, 0.53816843, 0.49040943],
       [0.26423119, 0.71382687, 0.83469766, 0.04292373, 0.78491584],
       [0.99315373, 0.67465299, 0.42820689, 0.10774601, 0.57097224]])

In [39]:
oneDa.size

15

In [40]:
np.reshape(oneDa, (oneDa.size,))    #flatten the 2D array oneDa to 1D array

array([0.59623166, 0.92751023, 0.78838537, 0.53816843, 0.49040943,
       0.26423119, 0.71382687, 0.83469766, 0.04292373, 0.78491584,
       0.99315373, 0.67465299, 0.42820689, 0.10774601, 0.57097224])

### Exercise 21:
Stack two NumPy arrays vertically.

In [41]:
array1 = np.random.randint(1,3 ,size = (1,5))
array2 = np.random.randint(5,7 ,size = (1,5))

In [42]:
array1 

array([[1, 1, 1, 2, 1]])

In [43]:
array2

array([[5, 5, 5, 5, 6]])

In [44]:
np.stack((array1, array2) , axis = 2)   #stack array1 and array2 vertically using stack function in numpy 

array([[[1, 5],
        [1, 5],
        [1, 5],
        [2, 5],
        [1, 6]]])

### Exercise 22:
Stack two NumPy arrays horizontally.

In [45]:
np.stack((array1, array2), axis = 1)    #stack array1 and array2 horizontally 

array([[[1, 1, 1, 2, 1],
        [5, 5, 5, 5, 6]]])

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [46]:
p = np.random.randint(3,13, size = (4,5))
p

array([[10,  7,  5, 10, 12],
       [ 5,  5,  8,  5, 10],
       [ 3,  3,  6,  8,  7],
       [ 3,  7,  3,  7, 10]])

In [47]:
np.split(p, [3,5] ,axis = 1)  #return sub-arrays of p[, :3] and p[,3:]

[array([[10,  7,  5],
        [ 5,  5,  8],
        [ 3,  3,  6],
        [ 3,  7,  3]]),
 array([[10, 12],
        [ 5, 10],
        [ 8,  7],
        [ 7, 10]]),
 array([], shape=(4, 0), dtype=int64)]

In [48]:
np.split(p, [3,5] ,axis = 0)  #return sub-arrays of p[:3, ] and p[ 3: ,]

[array([[10,  7,  5, 10, 12],
        [ 5,  5,  8,  5, 10],
        [ 3,  3,  6,  8,  7]]),
 array([[ 3,  7,  3,  7, 10]]),
 array([], shape=(0, 5), dtype=int64)]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [49]:
num = np.linspace(1,10, 20)

In [50]:
np.round(num , 2)    #round num to two decimal places

array([ 1.  ,  1.47,  1.95,  2.42,  2.89,  3.37,  3.84,  4.32,  4.79,
        5.26,  5.74,  6.21,  6.68,  7.16,  7.63,  8.11,  8.58,  9.05,
        9.53, 10.  ])

### Exercise 25:
Find the unique elements of a NumPy array.

In [51]:
array = np.array(['saif', 'saif', 'dinne', 'ahamada'])
np.unique(array)   # return the unique element of array 

array(['ahamada', 'dinne', 'saif'], dtype='<U7')

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [52]:
array = np.random.randint(4, 13, size = (4,5))

In [53]:
array

array([[ 8,  8,  9, 12,  4],
       [ 5,  6,  6, 10, 10],
       [11,  6, 10,  7,  7],
       [11,  6,  6,  9, 12]])

In [54]:
array[array<7] = 7

In [55]:
array

array([[ 8,  8,  9, 12,  7],
       [ 7,  7,  7, 10, 10],
       [11,  7, 10,  7,  7],
       [11,  7,  7,  9, 12]])

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [56]:
array.cumsum()      #compute the cumulative sun of the element in array 

array([  8,  16,  25,  37,  44,  51,  58,  65,  75,  85,  96, 103, 113,
       120, 127, 138, 145, 152, 161, 173])

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [57]:
array1 = np.random.randint(0,4, size = (4,5))

In [58]:
array1

array([[3, 2, 3, 2, 2],
       [1, 2, 1, 2, 0],
       [0, 2, 2, 1, 2],
       [1, 3, 2, 3, 3]])

In [59]:
non_zero_el = array1[array1 != 0]    #extract the non zero element in array1 and assign it in variable non_zero_el

In [60]:
non_zero_el

array([3, 2, 3, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 3, 2, 3, 3])

In [61]:
np.size(non_zero_el)    # get the number of non-zero element with the array1 

18

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [62]:
array2 = np.random.randint(3,14, size = (4,))

In [63]:
array2

array([10, 12, 10, 13])

In [64]:
np.sort(array2)   # sort arra2 in ascending order 

array([10, 10, 12, 13])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [65]:
matrice = np.random.randint(2,13, size = (3,3))

In [66]:
matrice

array([[ 4, 11,  8],
       [11, 11,  8],
       [ 3,  9,  7]])

In [67]:
# sum row-wise of matrice 3x3 matrix called matrice
np.sum(matrice , axis = 1)

array([23, 30, 19])

In [68]:
# sum column-wise of 3x3 matrix called matrice
np.sum(matrice, axis = 0)

array([18, 31, 23])

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [69]:
data = np.random.randint(3,14 ,size = (5,6))   #create a random integer array with shape (5,6)

In [70]:
data   #print data

array([[12,  9, 13,  9,  6,  4],
       [13, 10,  3,  7,  3,  5],
       [ 7,  8, 12,  3, 12, 10],
       [ 9,  3,  5,  6,  8,  3],
       [12,  6, 13, 10,  5, 11]])

In [71]:
min_data = np.min(data)                              # compute the min of data
max_data = np.max(data)                              # compute the max of data
norm_data = (data - min_data)/(max_data -  min_data) #compute the normalization 

In [72]:
norm_data

array([[0.9, 0.6, 1. , 0.6, 0.3, 0.1],
       [1. , 0.7, 0. , 0.4, 0. , 0.2],
       [0.4, 0.5, 0.9, 0. , 0.9, 0.7],
       [0.6, 0. , 0.2, 0.3, 0.5, 0. ],
       [0.9, 0.3, 1. , 0.7, 0.2, 0.8]])

### Exercise 32:
Create two NumPy arrays and find the dot product.

In [73]:
array1 = np.random.randint(2,7, size = (3,4))   #create a random integer array with shape (3,4) and assign it into array1
array2 = np.random.randint(1,5 , size = (4,5))  #create a random integer array  shape (4,5) and assign it into array2

In [74]:
# computing array1 dot array2
array1.dot(array2)

array([[44, 32, 54, 40, 40],
       [36, 24, 39, 30, 37],
       [38, 25, 46, 35, 42]])

### Exercise 33:
Find the trace of a square NumPy matrix.

In [75]:
matrice = np.random.randint(4,7 , size = (4,4))  #create a matrix of dimension 4x4 generating randomly with integr assign the value in matrice variable 

In [76]:
matrice     # print matrice

array([[5, 4, 5, 5],
       [5, 6, 4, 4],
       [5, 5, 6, 6],
       [5, 4, 6, 4]])

In [77]:
np.trace(matrice)    #compute the trace of matrice 

21

### Exercise 34:
Create a 2D array and swap two rows.

In [78]:
array1 = np.random.randint(7,23, size = (4,5))   # create 2D array with shape (4,5) and assign it into array1 variable 

In [79]:
array1    # print array1

array([[11, 18, 18, 11, 18],
       [19, 12,  8, 16, 19],
       [13, 14, 20, 14, 11],
       [20, 14, 20, 13, 21]])

In [80]:
#interchange two rows
array1[[0, 3]] = array1[[3, 0]]

array1

array([[20, 14, 20, 13, 21],
       [19, 12,  8, 16, 19],
       [13, 14, 20, 14, 11],
       [11, 18, 18, 11, 18]])

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [81]:
array1 = np.arange(2,21)      #create a 1D NumPy array and assign it into array1 variable

In [82]:
array1     #print array1 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [83]:
np.vstack(array1)      # convert array1 in column vectore

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

### Exercise 36:
Find the determinant of a 3x3 matrix.

In [84]:
array1 = np.random.randint(3,7, size = (3,3))   # create  a matrix with dimension 3x3 genereating with integer 

In [85]:
np.linalg.det(array1)

-2.999999999999998

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [86]:
matrice_22 = np.random.randint(2,10, size = (2,2))    #create a matrix with dimesion 2x2

In [87]:
np.linalg.eig(matrice_22)   #compute the eigen values and eigenvectors of matrice_22

(array([13.65685425,  2.34314575]),
 array([[ 0.57735027, -0.57735027],
        [ 0.81649658,  0.81649658]]))

### Exercise 38:
Solve a system of linear equations using NumPy.

assume that the equation is :
$$
x + y = 1 \\
x - y =2
$$

In [88]:
np.linalg.solve(np.array([[1,1], [1,-1]]), np.array([1,2]))   #solve this equation above

array([ 1.5, -0.5])

### Exercise 39:
Add Gaussian noise to a NumPy array.

In [89]:
array = np.random.randint(2,5, size = (5,4))   #create an array with shape (5,4) and assign it into 

In [90]:
array

array([[4, 4, 2, 2],
       [4, 4, 4, 3],
       [3, 3, 4, 2],
       [3, 3, 3, 4],
       [4, 3, 2, 4]])

In [91]:
gaussian_noise = np.random.randint(0,5 , size = (5,4))  # create a gaussian noise with the same shape as my array and assign the value in gaussian_noise 

In [92]:
gaussian_noise

array([[1, 2, 0, 4],
       [0, 1, 0, 4],
       [2, 1, 3, 0],
       [2, 3, 4, 4],
       [2, 2, 0, 0]])

In [93]:
array_noise = array + gaussian_noise   #add to my array the gaussian noise 

In [94]:
array_noise   #print array_noise

array([[5, 6, 2, 6],
       [4, 5, 4, 7],
       [5, 4, 7, 2],
       [5, 6, 7, 8],
       [6, 5, 2, 4]])

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [95]:
matrix_44 = np.random.randint(1,7, size = (4,4))   #create the matrix with dimension 4x4 and assign the value in matrix_44


In [96]:
matrix_44

array([[6, 1, 5, 3],
       [3, 1, 6, 3],
       [4, 3, 3, 3],
       [1, 3, 5, 6]])

In [97]:
np.diagonal(matrix_44)  # extract the diagonal of the matrix_44

array([6, 1, 3, 6])

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

In [98]:
array = np.random.randint(1,101, 100)    # create an array of 100 random values between 2 to 7   

In [99]:
np.sort(array[(array>=10) & (array<=50)])   #cliping the values of array to range between 10 to 50 

array([10, 11, 11, 11, 12, 14, 14, 15, 16, 17, 17, 18, 18, 21, 21, 23, 24,
       25, 29, 30, 30, 31, 31, 32, 34, 35, 36, 37, 37, 37, 38, 38, 38, 39,
       40, 40, 40, 41, 41, 41, 43, 45, 46, 47, 49, 49, 50, 50, 50])

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

In [100]:
array = np.random.randint(-5,5, size = (5,6))  #create a 2D array with shape of (5,6) filled with integer random value between -5 and 5

In [101]:
array

array([[-4, -2,  4, -3,  1, -4],
       [ 2,  2, -2, -4,  4,  2],
       [-4,  0, -5, -5, -5,  2],
       [-5,  3,  0,  2,  2,  1],
       [ 1, -5, -4, -5, -3, -4]])

In [102]:
array[array <= 0] = 0   #replace all negative value in array by 0 

In [103]:
array   # print the array without negative value 

array([[0, 0, 4, 0, 1, 0],
       [2, 2, 0, 0, 4, 2],
       [0, 0, 0, 0, 0, 2],
       [0, 3, 0, 2, 2, 1],
       [1, 0, 0, 0, 0, 0]])

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

In [104]:
array1 = np.random.randint(2,7,10)       # create an 1D array with shape (10,) and filled it with random integer between 2 to 7 and assign it to array 1 
array2 = np.random.randint(3,9, 10)      # # create an 1D array with shape (10,) and filled it with random integer between 3 to 9 and assign it to array 2

In [105]:
array1

array([6, 4, 6, 3, 5, 5, 3, 4, 4, 4])

In [106]:
array2

array([3, 7, 8, 8, 3, 7, 5, 8, 6, 3])

In [107]:
# inner product of array1 and array2
np.inner(array1, array2)

251

In [108]:
# outer product of array1 and array2
np.outer(array1, array2)

array([[18, 42, 48, 48, 18, 42, 30, 48, 36, 18],
       [12, 28, 32, 32, 12, 28, 20, 32, 24, 12],
       [18, 42, 48, 48, 18, 42, 30, 48, 36, 18],
       [ 9, 21, 24, 24,  9, 21, 15, 24, 18,  9],
       [15, 35, 40, 40, 15, 35, 25, 40, 30, 15],
       [15, 35, 40, 40, 15, 35, 25, 40, 30, 15],
       [ 9, 21, 24, 24,  9, 21, 15, 24, 18,  9],
       [12, 28, 32, 32, 12, 28, 20, 32, 24, 12],
       [12, 28, 32, 32, 12, 28, 20, 32, 24, 12],
       [12, 28, 32, 32, 12, 28, 20, 32, 24, 12]])

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

In [109]:
array1 = np.random.randint(1,7, 10)    
array2 = np.random.randint(11,17, 10)

In [110]:
array1

array([6, 1, 3, 6, 5, 1, 6, 6, 6, 4])

In [111]:
array2

array([13, 16, 11, 14, 14, 11, 15, 11, 16, 11])

In [112]:
distance = np.abs(array1 - array2)    # compute the distance between between array1 and array2

In [113]:
distance

array([ 7, 15,  8,  8,  9, 10,  9,  5, 10,  7])

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

In [114]:
matrix_55 = np.random.randint(2,13, size = (5,5))  

In [115]:
matrix_55

array([[11,  9,  4,  3,  4],
       [12, 10,  5, 12, 11],
       [ 7,  4, 11, 10,  5],
       [ 3,  4,  6,  8,  5],
       [11,  8,  8,  6,  4]])

In [116]:
np.unique(matrix_55, return_counts = True)     #count the occurrences of each unique value in matrix_55

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([2, 5, 3, 2, 1, 3, 1, 2, 4, 2]))

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

In [117]:
array = np.random.randint(3,5, size = (3,3))

In [118]:
array

array([[4, 4, 3],
       [4, 3, 4],
       [3, 4, 3]])

In [119]:
np.mean(array, axis = 1)

array([3.66666667, 3.66666667, 3.33333333])

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

In [120]:
array = np.random.randint(2,70,size = (5,5))

In [121]:
array>50    #check if any of the values are greater than 50

array([[ True, False, False,  True, False],
       [ True, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False,  True],
       [False, False, False,  True,  True]])

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

In [122]:
array1 = np.random.random(6)
array2 = np.random.random(6)

In [123]:
np.correlate(array1, array2)    #compute the Pearson correlation coefficient between  array1 and array2. 

array([2.40696601])

### Exercise 51:
Convert a NumPy array of radians to degrees.

In [124]:
array_rand = np.random.randint(0 , 2*3.14159265358979 , 12)

In [125]:
array_degree = (array_rand * 180)/3.14159265358979  #convert array_rand to degree

In [126]:
array_degree

array([ 57.29577951, 229.18311805, 229.18311805, 229.18311805,
         0.        ,  57.29577951, 229.18311805, 286.47889757,
       114.59155903, 229.18311805,   0.        , 286.47889757])

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

In [127]:
array = np.random.randint(2,7, 39)

In [128]:
#compute the variance 
np.var(array)

1.8974358974358974

In [129]:
#compute the standart deviation
np.std(array)

1.377474463442389

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

In [130]:
array3 = np.random.randint(2,12, size = (6,7))

In [131]:
array3

array([[ 6,  7,  2,  7,  2,  2,  8],
       [ 4,  9, 11,  6,  4,  7,  7],
       [10, 10,  4,  6, 10,  4,  9],
       [ 3,  5,  8,  5, 10,  4,  4],
       [ 6, 10, 11, 11,  7, 11,  3],
       [10,  8, 10, 10,  9, 11, 10]])

In [132]:
np.argmax(array3, axis = 1)      # return the index of the maximum values along each rows

array([6, 2, 0, 4, 2, 5])

In [133]:
np.argmax(array3, axis = 0)      # return the index of the maximum values along each columns

array([2, 2, 1, 4, 2, 4, 5])

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

In [134]:
matrix_22 = np.random.randint(1,6, size = (2,2))

In [135]:
np.invert(matrice_22)    # compute the inverse of matri_22

array([[-9, -5],
       [-9, -9]])

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

In [136]:
array4 = np.random.randint(3,17 , 10)

In [137]:
std_array4 = (array4 - np.mean(array4))/np.std(array4)   # compute the standardization of array4 

In [138]:
array4

array([ 8,  8, 12,  4,  6,  3,  6,  9,  5,  4])

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

In [139]:
array1 = np.arange(2,10)
array2 = np.arange(10,18)

In [140]:
array1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17])

In [142]:
#compute the addition of array1 and array2 
array1 + array2

array([12, 14, 16, 18, 20, 22, 24, 26])

In [143]:
#compute the sunstraction of array1 and array2
array1 - array2

array([-8, -8, -8, -8, -8, -8, -8, -8])

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

In [144]:
array = np.random.random(12)

In [145]:
array

array([0.22196268, 0.71208164, 0.08178261, 0.13166297, 0.31479195,
       0.21428427, 0.69931694, 0.93968341, 0.2636424 , 0.7796884 ,
       0.63624635, 0.49674394])

In [146]:
# find the index of the maximum element in array
np.argmax(array)

7

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

In [147]:
array33 = np.random.random((3,3))

In [148]:
array33

array([[0.37684782, 0.91117644, 0.62586475],
       [0.42842745, 0.47752802, 0.24524376],
       [0.26589908, 0.27223062, 0.19758571]])

In [149]:
#rotate array33 by 90 degrees
np.swapaxes(array33 ,1 ,0)

array([[0.37684782, 0.42842745, 0.26589908],
       [0.91117644, 0.47752802, 0.27223062],
       [0.62586475, 0.24524376, 0.19758571]])

### Exercise 59:
Compute the Frobenius norm of a matrix.

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

In [150]:
array7 = np.random.randint(3,19, size = (6,7))

In [151]:
array7

array([[ 8,  7,  8,  8, 18, 13, 11],
       [16, 14, 13, 18,  8, 10, 10],
       [18, 15, 12, 16, 14, 13,  6],
       [ 9,  8, 12, 15, 15, 11, 16],
       [12,  4,  3, 17, 17,  4, 18],
       [ 9,  6, 12,  3,  5, 12,  5]])

In [152]:
array7[3:,3:]   #subarray from the row of index 3 until the end and the column of index 3 until the end 

array([[15, 15, 11, 16],
       [17, 17,  4, 18],
       [ 3,  5, 12,  5]])